apiVersion: v1
kind: Service
metadata:
  labels:
    app: competition-db
  name: competition-db
spec:
  ports:
  - name: 30001to5432
    nodePort: 30001
    port: 5432
    targetPort: 5432
  selector:
    app: competition-db
  type: NodePort