apiVersion: v1
kind: Service
metadata:
  labels:
    app: competition-api
  name: competition-api
spec:
  ports:
  - name: 30002to8080
    nodePort: 30002
    port: 8080
    targetPort: 8080
  selector:
    app: competition-api
  type: NodePort