apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk11
          imagePullPolicy: Always
          name: jenkins
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 0
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: false
            - name: docker-directory
              mountPath: /var/lib/docker
              readOnly: false
      volumes:
        - name: jenkins-vol
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
        - name: docker-directory
          hostPath:
            path: "/var/lib/docker"
      nodeSelector:
        nodeType: worker